/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.unab.sipra.DocenteGui;

/**
 *
 * @author fabia
 */
public class perfilEstudiante extends javax.swing.JFrame {

    /**
     * Creates new form perfilEstudiante
     */
    public perfilEstudiante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cajaNombresApellidosPerfilEstudianteDocenteGui = new javax.swing.JTextField();
        cajaNumeroIdentificacionPerfilEstudianteDocenteGui = new javax.swing.JTextField();
        cajaCorreoPerfilEstudianteDocenteGui = new javax.swing.JTextField();
        cajaProgramaPerfilEstudianteDocenteGui = new javax.swing.JTextField();
        cajaNombreEmpresaPerfilEstudianteDocenteGui = new javax.swing.JTextField();
        cajaNombreJefeInmediatoPerfilEstudianteDocenteGui = new javax.swing.JTextField();
        cajaFotoPerfilEstudianteDocenteGui = new javax.swing.JPanel();
        botonCerrarPerfilEstudianteDocenteGui = new javax.swing.JButton();
        botonEditarPerfilEstudianteDocenteGui = new javax.swing.JButton();
        barraProgresoEditarPerfilEstudianteDocenteGui = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cajaActividadesEstdiantePerfilEstudianteDocenteGui = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perfil Del Estudiante");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cajaNombresApellidosPerfilEstudianteDocenteGui.setEditable(false);
        cajaNombresApellidosPerfilEstudianteDocenteGui.setBackground(new java.awt.Color(255, 255, 255));
        cajaNombresApellidosPerfilEstudianteDocenteGui.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cajaNombresApellidosPerfilEstudianteDocenteGui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        cajaNombresApellidosPerfilEstudianteDocenteGui.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(cajaNombresApellidosPerfilEstudianteDocenteGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 350, -1));

        cajaNumeroIdentificacionPerfilEstudianteDocenteGui.setEditable(false);
        cajaNumeroIdentificacionPerfilEstudianteDocenteGui.setBackground(new java.awt.Color(255, 255, 255));
        cajaNumeroIdentificacionPerfilEstudianteDocenteGui.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cajaNumeroIdentificacionPerfilEstudianteDocenteGui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(cajaNumeroIdentificacionPerfilEstudianteDocenteGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 320, -1));

        cajaCorreoPerfilEstudianteDocenteGui.setEditable(false);
        cajaCorreoPerfilEstudianteDocenteGui.setBackground(new java.awt.Color(255, 255, 255));
        cajaCorreoPerfilEstudianteDocenteGui.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cajaCorreoPerfilEstudianteDocenteGui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(cajaCorreoPerfilEstudianteDocenteGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 430, -1));

        cajaProgramaPerfilEstudianteDocenteGui.setEditable(false);
        cajaProgramaPerfilEstudianteDocenteGui.setBackground(new java.awt.Color(255, 255, 255));
        cajaProgramaPerfilEstudianteDocenteGui.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cajaProgramaPerfilEstudianteDocenteGui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(cajaProgramaPerfilEstudianteDocenteGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 420, -1));

        cajaNombreEmpresaPerfilEstudianteDocenteGui.setEditable(false);
        cajaNombreEmpresaPerfilEstudianteDocenteGui.setBackground(new java.awt.Color(255, 255, 255));
        cajaNombreEmpresaPerfilEstudianteDocenteGui.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cajaNombreEmpresaPerfilEstudianteDocenteGui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(cajaNombreEmpresaPerfilEstudianteDocenteGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 370, -1));

        cajaNombreJefeInmediatoPerfilEstudianteDocenteGui.setEditable(false);
        cajaNombreJefeInmediatoPerfilEstudianteDocenteGui.setBackground(new java.awt.Color(255, 255, 255));
        cajaNombreJefeInmediatoPerfilEstudianteDocenteGui.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cajaNombreJefeInmediatoPerfilEstudianteDocenteGui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(cajaNombreJefeInmediatoPerfilEstudianteDocenteGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 330, -1));

        cajaFotoPerfilEstudianteDocenteGui.setBackground(new java.awt.Color(255, 255, 255));
        cajaFotoPerfilEstudianteDocenteGui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        javax.swing.GroupLayout cajaFotoPerfilEstudianteDocenteGuiLayout = new javax.swing.GroupLayout(cajaFotoPerfilEstudianteDocenteGui);
        cajaFotoPerfilEstudianteDocenteGui.setLayout(cajaFotoPerfilEstudianteDocenteGuiLayout);
        cajaFotoPerfilEstudianteDocenteGuiLayout.setHorizontalGroup(
            cajaFotoPerfilEstudianteDocenteGuiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
        );
        cajaFotoPerfilEstudianteDocenteGuiLayout.setVerticalGroup(
            cajaFotoPerfilEstudianteDocenteGuiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );

        getContentPane().add(cajaFotoPerfilEstudianteDocenteGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 170, 150));

        botonCerrarPerfilEstudianteDocenteGui.setBackground(new java.awt.Color(102, 0, 0));
        botonCerrarPerfilEstudianteDocenteGui.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botonCerrarPerfilEstudianteDocenteGui.setForeground(new java.awt.Color(0, 0, 0));
        botonCerrarPerfilEstudianteDocenteGui.setText("CERRAR");
        botonCerrarPerfilEstudianteDocenteGui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        botonCerrarPerfilEstudianteDocenteGui.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(botonCerrarPerfilEstudianteDocenteGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, 90, 30));

        botonEditarPerfilEstudianteDocenteGui.setBackground(new java.awt.Color(102, 0, 0));
        botonEditarPerfilEstudianteDocenteGui.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botonEditarPerfilEstudianteDocenteGui.setForeground(new java.awt.Color(0, 0, 0));
        botonEditarPerfilEstudianteDocenteGui.setText("EDITAR");
        botonEditarPerfilEstudianteDocenteGui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        botonEditarPerfilEstudianteDocenteGui.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(botonEditarPerfilEstudianteDocenteGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 100, 30));

        barraProgresoEditarPerfilEstudianteDocenteGui.setBackground(new java.awt.Color(255, 255, 255));
        barraProgresoEditarPerfilEstudianteDocenteGui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        getContentPane().add(barraProgresoEditarPerfilEstudianteDocenteGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 310, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Avance del Estudiante");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("100%");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 40, 10));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("0%");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Actividades Que Realiza");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        cajaActividadesEstdiantePerfilEstudianteDocenteGui.setEditable(false);
        cajaActividadesEstdiantePerfilEstudianteDocenteGui.setBackground(new java.awt.Color(255, 255, 255));
        cajaActividadesEstdiantePerfilEstudianteDocenteGui.setColumns(20);
        cajaActividadesEstdiantePerfilEstudianteDocenteGui.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cajaActividadesEstdiantePerfilEstudianteDocenteGui.setRows(5);
        cajaActividadesEstdiantePerfilEstudianteDocenteGui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jScrollPane1.setViewportView(cajaActividadesEstdiantePerfilEstudianteDocenteGui);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 280, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabia\\OneDrive\\Escritorio\\NetBeansProjects\\SIPRA\\src\\main\\java\\com\\unab\\sipra\\recursos\\peril estudiante interfaz docente imagen.png")); // NOI18N
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 4, true));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 821, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(perfilEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(perfilEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(perfilEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(perfilEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new perfilEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JProgressBar barraProgresoEditarPerfilEstudianteDocenteGui;
    private javax.swing.JButton botonCerrarPerfilEstudianteDocenteGui;
    private javax.swing.JButton botonEditarPerfilEstudianteDocenteGui;
    private javax.swing.JTextArea cajaActividadesEstdiantePerfilEstudianteDocenteGui;
    private javax.swing.JTextField cajaCorreoPerfilEstudianteDocenteGui;
    private javax.swing.JPanel cajaFotoPerfilEstudianteDocenteGui;
    private javax.swing.JTextField cajaNombreEmpresaPerfilEstudianteDocenteGui;
    private javax.swing.JTextField cajaNombreJefeInmediatoPerfilEstudianteDocenteGui;
    private javax.swing.JTextField cajaNombresApellidosPerfilEstudianteDocenteGui;
    private javax.swing.JTextField cajaNumeroIdentificacionPerfilEstudianteDocenteGui;
    private javax.swing.JTextField cajaProgramaPerfilEstudianteDocenteGui;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
