/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.unab.sipra.EstudianteGui;

/**
 *
 * @author fabia
 */
public class agregarInformacionEmpresa extends javax.swing.JFrame {

    /**
     * Creates new form agregarInformacionEmpresa
     */
    public agregarInformacionEmpresa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cajaNombreEmpresaAggInfoEmpresa = new javax.swing.JTextField();
        cajaAreaQuieLaboraAggInfoEmpresa = new javax.swing.JTextField();
        botonGuardarAggInfoEmpresa = new javax.swing.JButton();
        cajaDireccionEmpresaAgregarInfoEmpresa = new javax.swing.JTextField();
        cajaNumeroContactoJefeAggInfoEmpresa = new javax.swing.JTextField();
        cajaNombreJefeInmediatoAggInfoEmpresa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        cajaActividadesQueRealizaAggInfoEmpresa = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agregar Infromacion Empresarial");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cajaNombreEmpresaAggInfoEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        cajaNombreEmpresaAggInfoEmpresa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cajaNombreEmpresaAggInfoEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        cajaNombreEmpresaAggInfoEmpresa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        getContentPane().add(cajaNombreEmpresaAggInfoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 700, -1));

        cajaAreaQuieLaboraAggInfoEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        cajaAreaQuieLaboraAggInfoEmpresa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cajaAreaQuieLaboraAggInfoEmpresa.setForeground(new java.awt.Color(0, 0, 0));
        cajaAreaQuieLaboraAggInfoEmpresa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        getContentPane().add(cajaAreaQuieLaboraAggInfoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 700, -1));

        botonGuardarAggInfoEmpresa.setBackground(new java.awt.Color(153, 0, 0));
        botonGuardarAggInfoEmpresa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botonGuardarAggInfoEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        botonGuardarAggInfoEmpresa.setText("GUARDAR");
        botonGuardarAggInfoEmpresa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        botonGuardarAggInfoEmpresa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(botonGuardarAggInfoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 440, 110, 30));

        cajaDireccionEmpresaAgregarInfoEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        cajaDireccionEmpresaAgregarInfoEmpresa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cajaDireccionEmpresaAgregarInfoEmpresa.setForeground(new java.awt.Color(0, 0, 0));
        cajaDireccionEmpresaAgregarInfoEmpresa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        getContentPane().add(cajaDireccionEmpresaAgregarInfoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 690, -1));

        cajaNumeroContactoJefeAggInfoEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        cajaNumeroContactoJefeAggInfoEmpresa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cajaNumeroContactoJefeAggInfoEmpresa.setForeground(new java.awt.Color(0, 0, 0));
        cajaNumeroContactoJefeAggInfoEmpresa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        getContentPane().add(cajaNumeroContactoJefeAggInfoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 610, -1));

        cajaNombreJefeInmediatoAggInfoEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        cajaNombreJefeInmediatoAggInfoEmpresa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cajaNombreJefeInmediatoAggInfoEmpresa.setForeground(new java.awt.Color(0, 0, 0));
        cajaNombreJefeInmediatoAggInfoEmpresa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        getContentPane().add(cajaNombreJefeInmediatoAggInfoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 680, -1));

        cajaActividadesQueRealizaAggInfoEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        cajaActividadesQueRealizaAggInfoEmpresa.setColumns(20);
        cajaActividadesQueRealizaAggInfoEmpresa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cajaActividadesQueRealizaAggInfoEmpresa.setForeground(new java.awt.Color(0, 0, 0));
        cajaActividadesQueRealizaAggInfoEmpresa.setRows(5);
        cajaActividadesQueRealizaAggInfoEmpresa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jScrollPane1.setViewportView(cajaActividadesQueRealizaAggInfoEmpresa);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 430, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabia\\OneDrive\\Escritorio\\NetBeansProjects\\SIPRA\\src\\main\\java\\com\\unab\\sipra\\recursos\\agrega informacion de la empresa imagen.png")); // NOI18N
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 4, true));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 981, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregarInformacionEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregarInformacionEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregarInformacionEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregarInformacionEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agregarInformacionEmpresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardarAggInfoEmpresa;
    private javax.swing.JTextArea cajaActividadesQueRealizaAggInfoEmpresa;
    private javax.swing.JTextField cajaAreaQuieLaboraAggInfoEmpresa;
    private javax.swing.JTextField cajaDireccionEmpresaAgregarInfoEmpresa;
    private javax.swing.JTextField cajaNombreEmpresaAggInfoEmpresa;
    private javax.swing.JTextField cajaNombreJefeInmediatoAggInfoEmpresa;
    private javax.swing.JTextField cajaNumeroContactoJefeAggInfoEmpresa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
