/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.unab.sipra.ExtensionGui;

/**
 *
 * @author fabia
 */
public class evidenciasDocente extends javax.swing.JFrame {

    /**
     * Creates new form evidenciasDocente
     */
    public evidenciasDocente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cajaFoto4EvidenciasDocenteExtensionGui = new javax.swing.JPanel();
        cajaFoto2EvidenciasDocenteExtensionGui = new javax.swing.JPanel();
        cajaFoto5EvidenciasDocenteExtensionGui = new javax.swing.JPanel();
        cajaFoto3EvidenciasDocenteExtensionGui = new javax.swing.JPanel();
        cajaFoto6EvidenciasDocenteExtensionGui = new javax.swing.JPanel();
        cajaFoto1EvidenciasDocenteExtensionGui = new javax.swing.JPanel();
        cajaFecha1EvidenciasDocenteGui = new javax.swing.JTextField();
        cajaFecha3EvidenciasDocenteExtensionGui = new javax.swing.JTextField();
        cajaFecha2EvidenciasDocenteExtensionGui = new javax.swing.JTextField();
        cajaFechaEvidenciasDocenteExtensionGui = new javax.swing.JTextField();
        cajaFecha4EvidenciasDocenteExtensionGui = new javax.swing.JTextField();
        cajaFecha6EvidenciasDocenteExtensionGui = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Evidencias Del Docente");
        setAlwaysOnTop(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cajaFoto4EvidenciasDocenteExtensionGui.setBackground(new java.awt.Color(255, 255, 255));
        cajaFoto4EvidenciasDocenteExtensionGui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        javax.swing.GroupLayout cajaFoto4EvidenciasDocenteExtensionGuiLayout = new javax.swing.GroupLayout(cajaFoto4EvidenciasDocenteExtensionGui);
        cajaFoto4EvidenciasDocenteExtensionGui.setLayout(cajaFoto4EvidenciasDocenteExtensionGuiLayout);
        cajaFoto4EvidenciasDocenteExtensionGuiLayout.setHorizontalGroup(
            cajaFoto4EvidenciasDocenteExtensionGuiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
        );
        cajaFoto4EvidenciasDocenteExtensionGuiLayout.setVerticalGroup(
            cajaFoto4EvidenciasDocenteExtensionGuiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );

        getContentPane().add(cajaFoto4EvidenciasDocenteExtensionGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 170, 150));

        cajaFoto2EvidenciasDocenteExtensionGui.setBackground(new java.awt.Color(255, 255, 255));
        cajaFoto2EvidenciasDocenteExtensionGui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        javax.swing.GroupLayout cajaFoto2EvidenciasDocenteExtensionGuiLayout = new javax.swing.GroupLayout(cajaFoto2EvidenciasDocenteExtensionGui);
        cajaFoto2EvidenciasDocenteExtensionGui.setLayout(cajaFoto2EvidenciasDocenteExtensionGuiLayout);
        cajaFoto2EvidenciasDocenteExtensionGuiLayout.setHorizontalGroup(
            cajaFoto2EvidenciasDocenteExtensionGuiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
        );
        cajaFoto2EvidenciasDocenteExtensionGuiLayout.setVerticalGroup(
            cajaFoto2EvidenciasDocenteExtensionGuiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );

        getContentPane().add(cajaFoto2EvidenciasDocenteExtensionGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 170, 150));

        cajaFoto5EvidenciasDocenteExtensionGui.setBackground(new java.awt.Color(255, 255, 255));
        cajaFoto5EvidenciasDocenteExtensionGui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        javax.swing.GroupLayout cajaFoto5EvidenciasDocenteExtensionGuiLayout = new javax.swing.GroupLayout(cajaFoto5EvidenciasDocenteExtensionGui);
        cajaFoto5EvidenciasDocenteExtensionGui.setLayout(cajaFoto5EvidenciasDocenteExtensionGuiLayout);
        cajaFoto5EvidenciasDocenteExtensionGuiLayout.setHorizontalGroup(
            cajaFoto5EvidenciasDocenteExtensionGuiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
        );
        cajaFoto5EvidenciasDocenteExtensionGuiLayout.setVerticalGroup(
            cajaFoto5EvidenciasDocenteExtensionGuiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );

        getContentPane().add(cajaFoto5EvidenciasDocenteExtensionGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 170, 150));

        cajaFoto3EvidenciasDocenteExtensionGui.setBackground(new java.awt.Color(255, 255, 255));
        cajaFoto3EvidenciasDocenteExtensionGui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        javax.swing.GroupLayout cajaFoto3EvidenciasDocenteExtensionGuiLayout = new javax.swing.GroupLayout(cajaFoto3EvidenciasDocenteExtensionGui);
        cajaFoto3EvidenciasDocenteExtensionGui.setLayout(cajaFoto3EvidenciasDocenteExtensionGuiLayout);
        cajaFoto3EvidenciasDocenteExtensionGuiLayout.setHorizontalGroup(
            cajaFoto3EvidenciasDocenteExtensionGuiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
        );
        cajaFoto3EvidenciasDocenteExtensionGuiLayout.setVerticalGroup(
            cajaFoto3EvidenciasDocenteExtensionGuiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );

        getContentPane().add(cajaFoto3EvidenciasDocenteExtensionGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 170, 150));

        cajaFoto6EvidenciasDocenteExtensionGui.setBackground(new java.awt.Color(255, 255, 255));
        cajaFoto6EvidenciasDocenteExtensionGui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        javax.swing.GroupLayout cajaFoto6EvidenciasDocenteExtensionGuiLayout = new javax.swing.GroupLayout(cajaFoto6EvidenciasDocenteExtensionGui);
        cajaFoto6EvidenciasDocenteExtensionGui.setLayout(cajaFoto6EvidenciasDocenteExtensionGuiLayout);
        cajaFoto6EvidenciasDocenteExtensionGuiLayout.setHorizontalGroup(
            cajaFoto6EvidenciasDocenteExtensionGuiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
        );
        cajaFoto6EvidenciasDocenteExtensionGuiLayout.setVerticalGroup(
            cajaFoto6EvidenciasDocenteExtensionGuiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );

        getContentPane().add(cajaFoto6EvidenciasDocenteExtensionGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, 170, 150));

        cajaFoto1EvidenciasDocenteExtensionGui.setBackground(new java.awt.Color(255, 255, 255));
        cajaFoto1EvidenciasDocenteExtensionGui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        javax.swing.GroupLayout cajaFoto1EvidenciasDocenteExtensionGuiLayout = new javax.swing.GroupLayout(cajaFoto1EvidenciasDocenteExtensionGui);
        cajaFoto1EvidenciasDocenteExtensionGui.setLayout(cajaFoto1EvidenciasDocenteExtensionGuiLayout);
        cajaFoto1EvidenciasDocenteExtensionGuiLayout.setHorizontalGroup(
            cajaFoto1EvidenciasDocenteExtensionGuiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
        );
        cajaFoto1EvidenciasDocenteExtensionGuiLayout.setVerticalGroup(
            cajaFoto1EvidenciasDocenteExtensionGuiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );

        getContentPane().add(cajaFoto1EvidenciasDocenteExtensionGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 170, 150));

        cajaFecha1EvidenciasDocenteGui.setEditable(false);
        cajaFecha1EvidenciasDocenteGui.setBackground(new java.awt.Color(51, 51, 51));
        cajaFecha1EvidenciasDocenteGui.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cajaFecha1EvidenciasDocenteGui.setForeground(new java.awt.Color(255, 255, 255));
        cajaFecha1EvidenciasDocenteGui.setText("Fecha 1");
        getContentPane().add(cajaFecha1EvidenciasDocenteGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 120, -1));

        cajaFecha3EvidenciasDocenteExtensionGui.setEditable(false);
        cajaFecha3EvidenciasDocenteExtensionGui.setBackground(new java.awt.Color(51, 51, 51));
        cajaFecha3EvidenciasDocenteExtensionGui.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cajaFecha3EvidenciasDocenteExtensionGui.setForeground(new java.awt.Color(255, 255, 255));
        cajaFecha3EvidenciasDocenteExtensionGui.setText("Fecha 3");
        getContentPane().add(cajaFecha3EvidenciasDocenteExtensionGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, 120, -1));

        cajaFecha2EvidenciasDocenteExtensionGui.setEditable(false);
        cajaFecha2EvidenciasDocenteExtensionGui.setBackground(new java.awt.Color(51, 51, 51));
        cajaFecha2EvidenciasDocenteExtensionGui.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cajaFecha2EvidenciasDocenteExtensionGui.setForeground(new java.awt.Color(255, 255, 255));
        cajaFecha2EvidenciasDocenteExtensionGui.setText("Fecha 2");
        getContentPane().add(cajaFecha2EvidenciasDocenteExtensionGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 120, -1));

        cajaFechaEvidenciasDocenteExtensionGui.setEditable(false);
        cajaFechaEvidenciasDocenteExtensionGui.setBackground(new java.awt.Color(51, 51, 51));
        cajaFechaEvidenciasDocenteExtensionGui.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cajaFechaEvidenciasDocenteExtensionGui.setForeground(new java.awt.Color(255, 255, 255));
        cajaFechaEvidenciasDocenteExtensionGui.setText("Fecha 5");
        getContentPane().add(cajaFechaEvidenciasDocenteExtensionGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 120, -1));

        cajaFecha4EvidenciasDocenteExtensionGui.setEditable(false);
        cajaFecha4EvidenciasDocenteExtensionGui.setBackground(new java.awt.Color(51, 51, 51));
        cajaFecha4EvidenciasDocenteExtensionGui.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cajaFecha4EvidenciasDocenteExtensionGui.setForeground(new java.awt.Color(255, 255, 255));
        cajaFecha4EvidenciasDocenteExtensionGui.setText("Fecha 4");
        getContentPane().add(cajaFecha4EvidenciasDocenteExtensionGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 120, -1));

        cajaFecha6EvidenciasDocenteExtensionGui.setEditable(false);
        cajaFecha6EvidenciasDocenteExtensionGui.setBackground(new java.awt.Color(51, 51, 51));
        cajaFecha6EvidenciasDocenteExtensionGui.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cajaFecha6EvidenciasDocenteExtensionGui.setForeground(new java.awt.Color(255, 255, 255));
        cajaFecha6EvidenciasDocenteExtensionGui.setText("Fecha 6");
        cajaFecha6EvidenciasDocenteExtensionGui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaFecha6EvidenciasDocenteExtensionGuiActionPerformed(evt);
            }
        });
        getContentPane().add(cajaFecha6EvidenciasDocenteExtensionGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, 120, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabia\\OneDrive\\Escritorio\\NetBeansProjects\\SIPRA\\src\\main\\java\\com\\unab\\sipra\\recursos\\imagen evidencias del docente rol extension.png")); // NOI18N
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 4, true));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cajaFecha6EvidenciasDocenteExtensionGuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaFecha6EvidenciasDocenteExtensionGuiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaFecha6EvidenciasDocenteExtensionGuiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(evidenciasDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(evidenciasDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(evidenciasDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(evidenciasDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new evidenciasDocente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cajaFecha1EvidenciasDocenteGui;
    private javax.swing.JTextField cajaFecha2EvidenciasDocenteExtensionGui;
    private javax.swing.JTextField cajaFecha3EvidenciasDocenteExtensionGui;
    private javax.swing.JTextField cajaFecha4EvidenciasDocenteExtensionGui;
    private javax.swing.JTextField cajaFecha6EvidenciasDocenteExtensionGui;
    private javax.swing.JTextField cajaFechaEvidenciasDocenteExtensionGui;
    private javax.swing.JPanel cajaFoto1EvidenciasDocenteExtensionGui;
    private javax.swing.JPanel cajaFoto2EvidenciasDocenteExtensionGui;
    private javax.swing.JPanel cajaFoto3EvidenciasDocenteExtensionGui;
    private javax.swing.JPanel cajaFoto4EvidenciasDocenteExtensionGui;
    private javax.swing.JPanel cajaFoto5EvidenciasDocenteExtensionGui;
    private javax.swing.JPanel cajaFoto6EvidenciasDocenteExtensionGui;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
