/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.unab.sipra.ExtensionGui;

/**
 *
 * @author fabia
 */
public class perfilDocente extends javax.swing.JFrame {

    /**
     * Creates new form perfilDocente
     */
    public perfilDocente() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cajaFotoPerfilDocenteExtensionGui = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cajaNombresApellidosPerfilDocenteEstensionGui = new javax.swing.JTextField();
        cajaNumeroIdPerfilDocenteExtensionGui = new javax.swing.JTextField();
        cajaProgramaPerfilDocenteExtensionGui = new javax.swing.JTextField();
        botonVerEvidenciasDocentePerfilDocenteExtensionGui = new javax.swing.JButton();
        botonListaDeEstudiantesAcargoPerfilDocenteExtensionGui = new javax.swing.JButton();
        botonCerrarPerfilDocenteExtensionGui = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perfil Docente");
        setAlwaysOnTop(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cajaFotoPerfilDocenteExtensionGui.setBackground(new java.awt.Color(255, 255, 255));
        cajaFotoPerfilDocenteExtensionGui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        javax.swing.GroupLayout cajaFotoPerfilDocenteExtensionGuiLayout = new javax.swing.GroupLayout(cajaFotoPerfilDocenteExtensionGui);
        cajaFotoPerfilDocenteExtensionGui.setLayout(cajaFotoPerfilDocenteExtensionGuiLayout);
        cajaFotoPerfilDocenteExtensionGuiLayout.setHorizontalGroup(
            cajaFotoPerfilDocenteExtensionGuiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );
        cajaFotoPerfilDocenteExtensionGuiLayout.setVerticalGroup(
            cajaFotoPerfilDocenteExtensionGuiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 214, Short.MAX_VALUE)
        );

        getContentPane().add(cajaFotoPerfilDocenteExtensionGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 200, 220));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombres Y Apellidos:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Numero de Identificación:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Programa:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        cajaNombresApellidosPerfilDocenteEstensionGui.setEditable(false);
        cajaNombresApellidosPerfilDocenteEstensionGui.setBackground(new java.awt.Color(255, 255, 255));
        cajaNombresApellidosPerfilDocenteEstensionGui.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cajaNombresApellidosPerfilDocenteEstensionGui.setForeground(new java.awt.Color(0, 0, 0));
        cajaNombresApellidosPerfilDocenteEstensionGui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(cajaNombresApellidosPerfilDocenteEstensionGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 390, 30));

        cajaNumeroIdPerfilDocenteExtensionGui.setEditable(false);
        cajaNumeroIdPerfilDocenteExtensionGui.setBackground(new java.awt.Color(255, 255, 255));
        cajaNumeroIdPerfilDocenteExtensionGui.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cajaNumeroIdPerfilDocenteExtensionGui.setForeground(new java.awt.Color(0, 0, 0));
        cajaNumeroIdPerfilDocenteExtensionGui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(cajaNumeroIdPerfilDocenteExtensionGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 360, 30));

        cajaProgramaPerfilDocenteExtensionGui.setEditable(false);
        cajaProgramaPerfilDocenteExtensionGui.setBackground(new java.awt.Color(255, 255, 255));
        cajaProgramaPerfilDocenteExtensionGui.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cajaProgramaPerfilDocenteExtensionGui.setForeground(new java.awt.Color(0, 0, 0));
        cajaProgramaPerfilDocenteExtensionGui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(cajaProgramaPerfilDocenteExtensionGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 460, 30));

        botonVerEvidenciasDocentePerfilDocenteExtensionGui.setBackground(new java.awt.Color(153, 0, 0));
        botonVerEvidenciasDocentePerfilDocenteExtensionGui.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botonVerEvidenciasDocentePerfilDocenteExtensionGui.setForeground(new java.awt.Color(255, 255, 255));
        botonVerEvidenciasDocentePerfilDocenteExtensionGui.setText("VER EVIDENCIAS DEL DOCENTE");
        botonVerEvidenciasDocentePerfilDocenteExtensionGui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        botonVerEvidenciasDocentePerfilDocenteExtensionGui.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(botonVerEvidenciasDocentePerfilDocenteExtensionGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 280, 50));

        botonListaDeEstudiantesAcargoPerfilDocenteExtensionGui.setBackground(new java.awt.Color(153, 0, 0));
        botonListaDeEstudiantesAcargoPerfilDocenteExtensionGui.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botonListaDeEstudiantesAcargoPerfilDocenteExtensionGui.setForeground(new java.awt.Color(255, 255, 255));
        botonListaDeEstudiantesAcargoPerfilDocenteExtensionGui.setText("LISTA DE ESTUDIANTES A CARGO ");
        botonListaDeEstudiantesAcargoPerfilDocenteExtensionGui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        botonListaDeEstudiantesAcargoPerfilDocenteExtensionGui.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(botonListaDeEstudiantesAcargoPerfilDocenteExtensionGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 260, 50));

        botonCerrarPerfilDocenteExtensionGui.setBackground(new java.awt.Color(153, 0, 0));
        botonCerrarPerfilDocenteExtensionGui.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonCerrarPerfilDocenteExtensionGui.setForeground(new java.awt.Color(255, 255, 255));
        botonCerrarPerfilDocenteExtensionGui.setText("CERRAR");
        botonCerrarPerfilDocenteExtensionGui.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCerrarPerfilDocenteExtensionGui.setFocusPainted(false);
        botonCerrarPerfilDocenteExtensionGui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarPerfilDocenteExtensionGuiActionPerformed(evt);
            }
        });
        getContentPane().add(botonCerrarPerfilDocenteExtensionGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabia\\OneDrive\\Escritorio\\NetBeansProjects\\SIPRA\\src\\main\\java\\com\\unab\\sipra\\recursos\\peril docente del rol extension.png")); // NOI18N
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 4, true));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarPerfilDocenteExtensionGuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarPerfilDocenteExtensionGuiActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonCerrarPerfilDocenteExtensionGuiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(perfilDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(perfilDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(perfilDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(perfilDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new perfilDocente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCerrarPerfilDocenteExtensionGui;
    private javax.swing.JButton botonListaDeEstudiantesAcargoPerfilDocenteExtensionGui;
    private javax.swing.JButton botonVerEvidenciasDocentePerfilDocenteExtensionGui;
    private javax.swing.JPanel cajaFotoPerfilDocenteExtensionGui;
    private javax.swing.JTextField cajaNombresApellidosPerfilDocenteEstensionGui;
    private javax.swing.JTextField cajaNumeroIdPerfilDocenteExtensionGui;
    private javax.swing.JTextField cajaProgramaPerfilDocenteExtensionGui;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
