/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.unab.sipra.ExtensionGui;

import com.unab.sipra.DocenteGui.*;

/**
 *
 * @author fabia
 */
public class perfilEstudianteAvance extends javax.swing.JFrame {

    /**
     * Creates new form perfilEstudiante
     */
    public perfilEstudianteAvance() {
        initComponents();
        setVisible(true);
        this.setLocationRelativeTo(this);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cajaNombreApellidoPerfilEstudianteExtensionGui = new javax.swing.JTextField();
        cajaNumeroIdPerfilEstudianteExtensionGui = new javax.swing.JTextField();
        cajaCorreoPerfilEstudianteExtensionGui = new javax.swing.JTextField();
        cajaProgramaPerfilEstudianteExtensionGui = new javax.swing.JTextField();
        cajaNombreEmpresaPerfilEstudianteExtensionGui = new javax.swing.JTextField();
        cajaNombreJefeInmediatoPerfilEstudianteExtensionGui = new javax.swing.JTextField();
        cajaFotoPerfilEstudianteExtensionGui = new javax.swing.JPanel();
        botonCerrarPerfilEstudianteDocenteGui = new javax.swing.JButton();
        barraProgresoPerfilEstudianteExtensionGui = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cajaActividadesEstudiantePerfilEstudianteExtensionGui = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perfil Del Estudiante");
        setAlwaysOnTop(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cajaNombreApellidoPerfilEstudianteExtensionGui.setEditable(false);
        cajaNombreApellidoPerfilEstudianteExtensionGui.setBackground(new java.awt.Color(255, 255, 255));
        cajaNombreApellidoPerfilEstudianteExtensionGui.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cajaNombreApellidoPerfilEstudianteExtensionGui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(cajaNombreApellidoPerfilEstudianteExtensionGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 350, -1));

        cajaNumeroIdPerfilEstudianteExtensionGui.setEditable(false);
        cajaNumeroIdPerfilEstudianteExtensionGui.setBackground(new java.awt.Color(255, 255, 255));
        cajaNumeroIdPerfilEstudianteExtensionGui.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cajaNumeroIdPerfilEstudianteExtensionGui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(cajaNumeroIdPerfilEstudianteExtensionGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 320, -1));

        cajaCorreoPerfilEstudianteExtensionGui.setEditable(false);
        cajaCorreoPerfilEstudianteExtensionGui.setBackground(new java.awt.Color(255, 255, 255));
        cajaCorreoPerfilEstudianteExtensionGui.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cajaCorreoPerfilEstudianteExtensionGui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(cajaCorreoPerfilEstudianteExtensionGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 430, -1));

        cajaProgramaPerfilEstudianteExtensionGui.setEditable(false);
        cajaProgramaPerfilEstudianteExtensionGui.setBackground(new java.awt.Color(255, 255, 255));
        cajaProgramaPerfilEstudianteExtensionGui.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cajaProgramaPerfilEstudianteExtensionGui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(cajaProgramaPerfilEstudianteExtensionGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 420, -1));

        cajaNombreEmpresaPerfilEstudianteExtensionGui.setEditable(false);
        cajaNombreEmpresaPerfilEstudianteExtensionGui.setBackground(new java.awt.Color(255, 255, 255));
        cajaNombreEmpresaPerfilEstudianteExtensionGui.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cajaNombreEmpresaPerfilEstudianteExtensionGui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(cajaNombreEmpresaPerfilEstudianteExtensionGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 370, -1));

        cajaNombreJefeInmediatoPerfilEstudianteExtensionGui.setEditable(false);
        cajaNombreJefeInmediatoPerfilEstudianteExtensionGui.setBackground(new java.awt.Color(255, 255, 255));
        cajaNombreJefeInmediatoPerfilEstudianteExtensionGui.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cajaNombreJefeInmediatoPerfilEstudianteExtensionGui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(cajaNombreJefeInmediatoPerfilEstudianteExtensionGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 330, -1));

        cajaFotoPerfilEstudianteExtensionGui.setBackground(new java.awt.Color(255, 255, 255));
        cajaFotoPerfilEstudianteExtensionGui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        javax.swing.GroupLayout cajaFotoPerfilEstudianteExtensionGuiLayout = new javax.swing.GroupLayout(cajaFotoPerfilEstudianteExtensionGui);
        cajaFotoPerfilEstudianteExtensionGui.setLayout(cajaFotoPerfilEstudianteExtensionGuiLayout);
        cajaFotoPerfilEstudianteExtensionGuiLayout.setHorizontalGroup(
            cajaFotoPerfilEstudianteExtensionGuiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );
        cajaFotoPerfilEstudianteExtensionGuiLayout.setVerticalGroup(
            cajaFotoPerfilEstudianteExtensionGuiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );

        getContentPane().add(cajaFotoPerfilEstudianteExtensionGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 130, 120));

        botonCerrarPerfilEstudianteDocenteGui.setBackground(new java.awt.Color(153, 0, 0));
        botonCerrarPerfilEstudianteDocenteGui.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botonCerrarPerfilEstudianteDocenteGui.setForeground(new java.awt.Color(255, 255, 255));
        botonCerrarPerfilEstudianteDocenteGui.setText("CERRAR");
        botonCerrarPerfilEstudianteDocenteGui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        botonCerrarPerfilEstudianteDocenteGui.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(botonCerrarPerfilEstudianteDocenteGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, 90, 30));

        barraProgresoPerfilEstudianteExtensionGui.setBackground(new java.awt.Color(255, 255, 255));
        barraProgresoPerfilEstudianteExtensionGui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        getContentPane().add(barraProgresoPerfilEstudianteExtensionGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 310, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Avance del Estudiante");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("100%");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 40, 10));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("0%");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Actividades Que Realiza");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        cajaActividadesEstudiantePerfilEstudianteExtensionGui.setEditable(false);
        cajaActividadesEstudiantePerfilEstudianteExtensionGui.setBackground(new java.awt.Color(255, 255, 255));
        cajaActividadesEstudiantePerfilEstudianteExtensionGui.setColumns(20);
        cajaActividadesEstudiantePerfilEstudianteExtensionGui.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cajaActividadesEstudiantePerfilEstudianteExtensionGui.setRows(5);
        cajaActividadesEstudiantePerfilEstudianteExtensionGui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        cajaActividadesEstudiantePerfilEstudianteExtensionGui.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(cajaActividadesEstudiantePerfilEstudianteExtensionGui);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 290, 140));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Docente A Cargo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, -1, -1));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 270, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabia\\OneDrive\\Escritorio\\NetBeansProjects\\SIPRA\\src\\main\\java\\com\\unab\\sipra\\recursos\\peril estudiante interfaz docente imagen.png")); // NOI18N
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 4, true));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 821, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(perfilEstudianteAvance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(perfilEstudianteAvance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(perfilEstudianteAvance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(perfilEstudianteAvance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new perfilEstudianteAvance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgresoPerfilEstudianteExtensionGui;
    private javax.swing.JButton botonCerrarPerfilEstudianteDocenteGui;
    private javax.swing.JTextArea cajaActividadesEstudiantePerfilEstudianteExtensionGui;
    private javax.swing.JTextField cajaCorreoPerfilEstudianteExtensionGui;
    private javax.swing.JPanel cajaFotoPerfilEstudianteExtensionGui;
    private javax.swing.JTextField cajaNombreApellidoPerfilEstudianteExtensionGui;
    private javax.swing.JTextField cajaNombreEmpresaPerfilEstudianteExtensionGui;
    private javax.swing.JTextField cajaNombreJefeInmediatoPerfilEstudianteExtensionGui;
    private javax.swing.JTextField cajaNumeroIdPerfilEstudianteExtensionGui;
    private javax.swing.JTextField cajaProgramaPerfilEstudianteExtensionGui;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
