package com.unab.sipra.LoguinGui;

import com.unab.sipra.DocenteGui.interfazDocente;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author fabia
 */
public final class LoguinSipra extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public LoguinSipra() {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
    }

   
    

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cajaUsuarioLoguinSipraGui = new javax.swing.JTextField();
        cajaContraseñaLoguinSipraGui = new javax.swing.JPasswordField();
        cajaCheckEstudianteLoguinSipraGui = new javax.swing.JCheckBox();
        cajaCheckDocenteLoguinSipraGui = new javax.swing.JCheckBox();
        cajaCheckExtensionLoguinSipraGui = new javax.swing.JCheckBox();
        botonInicioSesionLoguinGui = new javax.swing.JButton();
        botonOlvidasteUsuarioContraseña = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loguin Sipra");
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cajaUsuarioLoguinSipraGui.setBackground(new java.awt.Color(255, 255, 255));
        cajaUsuarioLoguinSipraGui.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cajaUsuarioLoguinSipraGui.setForeground(new java.awt.Color(0, 0, 0));
        cajaUsuarioLoguinSipraGui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 3, true));
        cajaUsuarioLoguinSipraGui.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(cajaUsuarioLoguinSipraGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 280, 30));

        cajaContraseñaLoguinSipraGui.setBackground(new java.awt.Color(255, 255, 255));
        cajaContraseñaLoguinSipraGui.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cajaContraseñaLoguinSipraGui.setForeground(new java.awt.Color(0, 0, 0));
        cajaContraseñaLoguinSipraGui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 3, true));
        cajaContraseñaLoguinSipraGui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaContraseñaLoguinSipraGuiActionPerformed(evt);
            }
        });
        getContentPane().add(cajaContraseñaLoguinSipraGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 312, 280, 30));

        cajaCheckEstudianteLoguinSipraGui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        cajaCheckEstudianteLoguinSipraGui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaCheckEstudianteLoguinSipraGuiActionPerformed(evt);
            }
        });
        getContentPane().add(cajaCheckEstudianteLoguinSipraGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 20, 20));
        getContentPane().add(cajaCheckDocenteLoguinSipraGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));
        getContentPane().add(cajaCheckExtensionLoguinSipraGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, -1, -1));

        botonInicioSesionLoguinGui.setBackground(new java.awt.Color(204, 0, 0));
        botonInicioSesionLoguinGui.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        botonInicioSesionLoguinGui.setForeground(new java.awt.Color(255, 255, 255));
        botonInicioSesionLoguinGui.setText("EMPEZAR");
        botonInicioSesionLoguinGui.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        botonInicioSesionLoguinGui.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonInicioSesionLoguinGui.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonInicioSesionLoguinGuiMouseClicked(evt);
            }
        });
        botonInicioSesionLoguinGui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInicioSesionLoguinGuiActionPerformed(evt);
            }
        });
        getContentPane().add(botonInicioSesionLoguinGui, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 160, 40));

        botonOlvidasteUsuarioContraseña.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        botonOlvidasteUsuarioContraseña.setForeground(new java.awt.Color(0, 0, 0));
        botonOlvidasteUsuarioContraseña.setText("¿Olvidaste tu usuario o contraseña?");
        botonOlvidasteUsuarioContraseña.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonOlvidasteUsuarioContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonOlvidasteUsuarioContraseñaMouseClicked(evt);
            }
        });
        getContentPane().add(botonOlvidasteUsuarioContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 180, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabia\\OneDrive\\Escritorio\\NetBeansProjects\\SIPRA\\src\\main\\java\\com\\unab\\sipra\\recursos\\loginSipra00.png")); // NOI18N
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 4, true));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cajaContraseñaLoguinSipraGuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaContraseñaLoguinSipraGuiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaContraseñaLoguinSipraGuiActionPerformed

    private void cajaCheckEstudianteLoguinSipraGuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaCheckEstudianteLoguinSipraGuiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaCheckEstudianteLoguinSipraGuiActionPerformed

    private void botonInicioSesionLoguinGuiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicioSesionLoguinGuiMouseClicked
         String Usuario, Contraseña=null;
        Usuario=cajaUsuarioLoguinSipraGui.getText();
        Contraseña=cajaContraseñaLoguinSipraGui.getText();
    if(Usuario.equals("admin") && Contraseña.equals("admin")){
            interfazDocente docente = new interfazDocente();
            docente.setVisible(true);
            this.dispose();
           
        }else{
            JOptionPane.showMessageDialog(null,"CONTRASEÑA O USUARIO INCORRECTA");
        }
    }//GEN-LAST:event_botonInicioSesionLoguinGuiMouseClicked

    private void botonOlvidasteUsuarioContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonOlvidasteUsuarioContraseñaMouseClicked
        JOptionPane.showMessageDialog(null, "DIRIGETE AL DEPARTAMENTO DE SISTEMAS");
    }//GEN-LAST:event_botonOlvidasteUsuarioContraseñaMouseClicked

    private void botonInicioSesionLoguinGuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInicioSesionLoguinGuiActionPerformed
       
    }//GEN-LAST:event_botonInicioSesionLoguinGuiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoguinSipra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoguinSipra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoguinSipra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoguinSipra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LoguinSipra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonInicioSesionLoguinGui;
    private javax.swing.JLabel botonOlvidasteUsuarioContraseña;
    private javax.swing.JCheckBox cajaCheckDocenteLoguinSipraGui;
    private javax.swing.JCheckBox cajaCheckEstudianteLoguinSipraGui;
    private javax.swing.JCheckBox cajaCheckExtensionLoguinSipraGui;
    private javax.swing.JPasswordField cajaContraseñaLoguinSipraGui;
    private javax.swing.JTextField cajaUsuarioLoguinSipraGui;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private static class image {

        public image() {
        }
    }
}
